VeryGoodOpenSource/very_good_workflows

.github/workflows/dart_package.yml, README.md
**Optional** Which Dart SDK version to use. It can be a version (e.g. `2.12.0`) or a channel (e.g. `stable`):
**Default** `"stable"`
=> feat(dart_package): support dart_sdk input

.github/workflows/flutter_package.yml, README.md
- feat(flutter_package): support flutter_version, flutter_channel inputs
**Optional** The Flutter release channel to use (e.g. `stable`).
**Default** `"stable"`
**Optional** The Flutter SDK version to use (e.g. `2.8.1`).
**Default** `""`
=> feat(flutter_package): support flutter_version, flutter_channel inputs

CHANGELOG.md
- chore: v1.0.0
- rename to flutter_package.yml ([dedd17b](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/dedd17b9eb90bc9427e302bd6e4f8ccd1a0c3bd2))
- **dart_package:** support dart_sdk input ([#2](https://github.com/VeryGoodOpenSource/very_good_workflows/issues/2)) ([8964e1a](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/8964e1a4f3e5a61e434f655f730fc2a6d1622325))
- **flutter_package:** support flutter_version and flutter_channel inputs ([#5](https://github.com/VeryGoodOpenSource/very_good_workflows/issues/5)) ([99c0a0e](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/99c0a0e91dcd8ee6b01e10d79920f178da168d68))
- create dart_package and flutter_package workflows ([07e989f](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/ …
=> chore: v1.0.0

.github/workflows/dart_package.yml, .github/workflows/flutter_package.yml
- feat: enhance workflow step names
=> feat: enhance workflow step names

CHANGELOG.md
- enhance workflow step names ([#9](https://github.com/VeryGoodOpenSource/very_good_workflows/issues/9)) ([6429f08](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/6429f0849fa0d6b9dc845d6f00d62e4a3d875ff1))
=> chore: v1.0.1

README.md
- docs: add link to workflows blog
=> docs: add link to workflows blog

.github/workflows/dart_package.yml, .github/workflows/flutter_package.yml
- feat: upgrade to very_good_coverage@v1
=> feat: upgrade to very_good_coverage@v1

CHANGELOG.md
=> chore: v1.0.2

.github/workflows/dart_package.yml, .github/workflows/flutter_package.yml, README.md
Supports min_coverage property of very_good_coverage
=> feat: support min_coverage

CHANGELOG.md
- support min_coverage ([#11](https://github.com/VeryGoodOpenSource/very_good_workflows/issues/11)) ([a89e8b1](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/a89e8b1d7687b769ae5f975fff5568156f282887))
=> chore: v1.1.0

.github/workflows/flutter_package.yml
- feat(flutter_package): use very_good test runner
=> feat(flutter_package): use very_good test runner

CHANGELOG.md
- **flutter_package:** use very_good test runner ([#17](https://github.com/VeryGoodOpenSource/very_good_workflows/issues/17)) ([37174b1](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/37174b1cd607d13ad9f9f398d15a1725bccc95aa))
=> chore: v1.1.1

.github/workflows/flutter_package.yml, README.md
Adding the ability to disable test optimization
=> feat: ability to disable test optimization

CHANGELOG.md
- ability to disable test optimization ([#24](https://github.com/VeryGoodOpenSource/very_good_workflows/issues/24)) ([d6dc6a6](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/d6dc6a64bf7abd70ce42b1278001b65164bc7345))
- ability to run test recursively ([#25](https://github.com/VeryGoodOpenSource/very_good_workflows/issues/25)) ([a1c7235](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/a1c7235cd71b479f6d44657c67afe8a22bbbec21))
=> chore: v1.2.0

.github/workflows/ci.yml, .github/workflows/dart_package.yml
- fix(dart_package): use dart test instead of test_coverage
=> fix(dart_package): use dart test instead of test_coverage

.github/workflows/ci.yml, .github/workflows/dart_package.yml
- fix(dart_package): pin coverage to 1.2.0
=> fix(dart_package): pin coverage to 1.2.0

.github/workflows/dart_package.yml, README.md
- feat(dart_package): add optional concurrency input
=> feat(dart_package): add optional concurrency input

.github/workflows/flutter_package.yml, README.md
- feat(flutter_package): add optional concurrency input
=> feat(flutter_package): add optional concurrency input

CHANGELOG.md
=> chore: v1.3.0

.github/workflows/dart_package.yml, .github/workflows/flutter_package.yml
- fix: only run semantic commit step on pull_request
=> fix: only run semantic commit step on pull_request

.github/workflows/dart_package.yml
- feat(dart_package): analyze test directory
=> feat(dart_package): analyze test directory

.github/workflows/ci.yml, .github/workflows/semantic_pull_request.yml, README.md
- feat(semantic_pull_request): add semantic pull request workflow
=> feat(semantic_pull_request): add semantic pull request workflow

README.md
- docs(README): add semantic_pull_request workflow
=> docs(README): add semantic_pull_request workflow

CHANGELOG.md
=> chore: v1.4.0

CHANGELOG.md
=> chore: v1.5.0

.github/workflows/ci.yml, .github/workflows/semantic_pull_request.yml
- fix(semantic_pull_request): remove wip (write access)
=> fix(semantic_pull_request): remove wip (write access)

CHANGELOG.md
=> chore: v1.5.1

.github/workflows/dart_package.yml, README.md
- feat(dart_package): add runs_on input
=> feat(dart_package): add runs_on input

CHANGELOG.md
=> chore: v1.5.2

.github/workflows/flutter_package.yml, README.md
- feat(flutter_package): add runs_on input
=> feat(flutter_package): add runs_on input

CHANGELOG.md
- **flutter_package:** add runs_on input ([#59](https://github.com/VeryGoodOpenSource/very_good_workflows/issues/59)) ([5997890](https://github.com/VeryGoodOpenSource/very_good_workflows/commit/5997890627e530ac98d7af9f0850b92054dd10e7))
=> chore: v1.5.3

.github/workflows/ci.yml, .github/workflows/pana.yml, README.md
- feat: add new `pana` reusable workflow to verify package scores on pub.dev
The pana workflow consists of the following steps:
1. Install Pana
2. Verify Pana Score
**Optional** Which version of `package:pana` to use (e.g. `0.21.15`).
**Optional** The minimum score allowed.
**Default** 120
**Optional** The path to the root of the Dart package.
**Default** `"."`
**Optional** An optional operating system on which to run the workflow.
**Default** `"ubuntu-latest"`
```yaml
name: My Workflow
on: pull_request
jobs:
build:
uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
with:
min_score: 100
working_directory: "examples/my_flutter_package"
```
=> feat: add pana workflow

CHANGELOG.md, README.md
=> chore: v1.5.4

examples/dart_package/analysis_options.yaml, examples/dart_package/pubspec.yaml, examples/flutter_package/analysis_options.yaml, examples/flutter_package/pubspec.yaml
Bumping the versions of the example
=> chore: bump example versions

.github/workflows/dart_package.yml
Fixes #66 due to `.packages` deprecation from Dart 2.18 release.
=> fix: remove deprecated packages option:`.packages` -> `.dart_tool/package_config.json`

.github/workflows/ci.yml, examples/dart_package/pubspec.yaml, examples/flutter_package/pubspec.lock, examples/flutter_package/pubspec.yaml
- chore: upgrade to Flutter 3.3 and Dart 2.18
=> chore: upgrade to Flutter 3.3 and Dart 2.18

CHANGELOG.md
=> chore: v1.6.0

.github/workflows/ci.yml, .github/workflows/dart_package.yml, README.md
- feat(dart_package): add platform input
=> feat(dart_package): add platform input

CHANGELOG.md
=> chore: v1.7.0

.github/workflows/dart_package.yml, .github/workflows/flutter_package.yml
- feat: upgrade dart and flutter package to very_good_coverage@v2
=> feat: upgrade dart and flutter package to very_good_coverage@v2

.github/workflows/ci.yml, CHANGELOG.md
=> chore: v1.8.0

.github/workflows/ci.yml, .github/workflows/semantic_pull_request.yml, README.md
New inputs in the `semantic pull request`:
**Types:** Configure which types are allowed.
**Scopes:** Configure which scopes are allowed.
=> feat(semantic_pull_request): add types and scopes inputs

.github/cspell.json, .github/workflows/ci.yml, CHANGELOG.md, README.md
=> chore: v1.9.0

.github/workflows/ci.yml
=> ci: add deps to scopes

.github/workflows/ci.yml, .github/workflows/dart_package.yml, .github/workflows/flutter_package.yml, README.md
- feat: add optional setup step to flutter and dart package workflows (closes #41)
=> feat: add optional setup step to flutter and dart package workflows

CHANGELOG.md
=> chore: v1.10.0

.github/workflows/flutter_package.yml
Reference: https://github.com/VeryGoodOpenSource/very_good_workflows/issues/75#issuecomment-1291994529
=> feat: add cache key options

CHANGELOG.md
=> chore: v1.11.0

.github/workflows/flutter_package.yml
Since flutter format was deprecated in favor of `dart format`, the format step was breaking even if no issues with the formatting was present in the code.
This PR changes to suggested replacement to fix the issue.
Fixes #92
=> feat: replace flutter format with dart format

CHANGELOG.md
=> chore: v1.12.0

.github/workflows/flutter_package.yml, README.md
This option already exists in the `dart_package`, just adding it to the `flutter_package` as well.
=> feat: add analyze directories option to flutter package

.github/workflows/ci.yml, examples/dart_package/analysis_options.yaml, examples/dart_package/lib/dart_package.dart, examples/dart_package/pubspec.yaml, examples/flutter_package/analysis_options.yaml, examples/flutter_package/lib/flutter_package.dart, examples/flutter_package/pubspec.lock, examples/flutter_package/pubspec.yaml
=> chore: update examples

.github/workflows/flutter_package.yml, README.md
Resolves #94 
Changes:
- Adds a new input `package_get_excludes` to Flutter package workflow (`flutter_package`)
=> feat: support excluding directories

.github/cspell.json, .github/workflows/dart_pub_publish.yml, .github/workflows/flutter_pub_publish.yml, README.md
Add a `flutter` and `dart` publish script
=> feat: add publish scripts

.github/workflows/brick_publish.yml, .github/workflows/mason_publish.yml, README.md
Automate publishing bricks using [mason](https://brickhub.dev).
=> feat: add mason publish workflow

CHANGELOG.md
=> chore: v1.13.0

site/docusaurus.config.js, site/package.json
update docusaurus config with correct url
=> docs: update my-docs-site

.github/workflows/site.yaml, .github/workflows/site_deploy.yaml, site/docusaurus.config.js, site/package-lock.json, site/src/pages/index.tsx, site/static/CNAME
=> docs: add workflows for docs

.github/workflows/site_deploy.yaml
=> build: fix deploy workflow

site/docs/workflows/dart_pub_publish.md, site/docs/workflows/flutter_pub_publish.md, site/docs/workflows/mason_publish.md
@wolfenrain told me to fix this.
=> feat: update docs

site/docusaurus.config.js, site/src/css/custom.css
Update theming, mostly on night mode
=> docs: update theming

site/docs/workflows/dart_pub_publish.md
=> docs: fix link in dart_pub_publish.md

.github/workflows/ci.yml, site/docs/workflows/semantic_pull_request.md
Adds a new section to the semantic pull requests documentation to explain github token permission issues.
Fixes #129
=> docs: add github permissions section to semantic pull request workflow

site/docs/workflows/pana.md
docs: link to pana versions page
=> docs: link to pana versions page

.github/workflows/flutter_package.yml
With latest `very_good_cli` 0.16.0 the analytics were removed and the `--analytics` command is not further available.
=> fix: remove need for disabling analytics due to cli update

CHANGELOG.md
- feat: Add `format_directories` option ([#113](https://github.com/VeryGoodOpenSource/very_good_workflows/pull/113))
- feat: add `format_line_length` input ([#114](https://github.com/VeryGoodOpenSource/very_good_workflows/pull/114))
- build: fix deploy workflow ([#122](https://github.com/VeryGoodOpenSource/very_good_workflows/pull/122))
- feat: add ssh key setup step ([#131](https://github.com/VeryGoodOpenSource/very_good_workflows/pull/131))
- docs: add cspell example ([#134](https://github.com/VeryGoodOpenSource/very_good_workflows/pull/134))
- docs: link to pana versions page ([#141](https://github.com/VeryGoodOpenSource/very_good_workflows/pull/141))
- fix: remove analytics due to cli update ([#143](https://github.com/VeryGoodOpenSource/very_good_workflows/pull/143))
=> chore: v1.14.0

.github/cspell.json, tool/release_ready.sh
chore: add release script to generate changelogs
=> chore: add release script to generate changelogs

.github/cspell.json, CHANGELOG.md
=> chore: v1.15.0

.github/workflows/dart_pub_publish.yml, .github/workflows/flutter_pub_publish.yml, .github/workflows/mason_publish.yml
**READY**
Closes #133 as the default timeout is 5 minutes to which one can argue is better than 6 hours.
=> feat: add timeout input to the publish workflows

CHANGELOG.md
=> chore: v1.16.0

CHANGELOG.md
**READY**
For changes refer to the CHANGELOG.
Resolves #171
=> chore: v1.16.1

.github/workflows/dart_pub_publish.yml, .github/workflows/flutter_pub_publish.yml, .github/workflows/mason_publish.yml, site/docs/workflows/dart_pub_publish.md, site/docs/workflows/flutter_pub_publish.md, site/docs/workflows/mason_publish.md
**READY**
Moving to `secrets` input
Closes #172
=> fix: use `secrets` for credential information

.github/dependabot.yaml
**READY**
Adding the website into dependabot as it was missing and causing other security errors.
=> chore: add dependabot for docs site

.github/workflows/dart_package.yml
=> fix: change skip_example to no_example

site/docs/workflows/dart_package.md
**READY**
Introduces the documentation for the new argument `no_example `.
=> docs: add no_example docs

.github/ISSUE_TEMPLATE/feature_request.md
Ready to review.
Fixes #232.
This PR adds a feature request template.
=> feat: Add feature request template

.github/workflows/ci.yml
**READY**
Updating the version of Flutter and Pana being used in this repo's CI config
=> chore: update Flutter version in CI

site/docs/workflows/dart_package.md, site/docs/workflows/dart_pub_publish.md, site/docs/workflows/flutter_package.md, site/docs/workflows/flutter_pub_publish.md, site/docs/workflows/license_check.md
=> chore: update docs for new flutter version

site/docusaurus.config.js
**READY**
Fixes #287. Updating docs site to point to new VGV Dev page.
=> docs: update vgv dev URL

site/package-lock.json, site/package.json
=> chore: update react version from 19.1.1 to 19.2.0
